[tox]
requires =
    tox>=4.24.1
    tox-uv>=1.25
env_list =
    py314-django{61, 60, 52}
    py313-django{61, 60, 52}
    py312-django{61, 60, 52}
    py311-django52
    py310-django52
    docs

[testenv]
runner = uv-venv-lock-runner
package = wheel
wheel_build_env = .pkg
set_env =
    PYTHONDEVMODE = 1
commands =
    python -W error -m coverage run -m pytest {posargs}
dependency_groups =
    test
    django52: django52
    django60: django60
    django61: django61

[testenv:docs]
base_python = python3.14
commands =
    sphinx-build -W --keep-going -b html docs docs/_build/html
dependency_groups =
    docs
